languageCode: en-us
title: Carol Kappus
theme: carolkappus
related:
  includeNewer: true
  threshold: 0
  indices:
    - name: Type # The name of the indice, same as Front Matter's .Param key.
      weight: 100 # We don't really need this, but omitting it would disable the indice.
      includeNewer: true # Here our relationship is timeless! This prevents Hugo from ignoring newer posts.
markup:
  goldmark:
    renderer:
      unsafe: true
enableEmoji: true
